packages:
  - "sdks/*"
  - "packages/common/mahjong/*"
  - "apps/sdkwork-mahjong-pc/packages/*"
  - "../sdkwork-utils/packages/sdkwork-utils-typescript"

catalog:
  "@types/node": ^25.5.2
  typescript: ~6.0.2
